"""
Configuration module for Portfolio Dashboard
"""

from .style import CUSTOM_CSS
from .constants import *

__all__ = ['CUSTOM_CSS', 'PAGE_CONFIG', 'DEFAULT_YAML_PATH', 'DEFAULT_DATE_RANGE_DAYS',
           'DEFAULT_CONFIDENCE_LEVEL', 'DEFAULT_PORTFOLIO_VALUE', 'DEFAULT_RISK_FREE_RATE',
           'DEFAULT_NUM_PORTFOLIOS', 'DEFAULT_BATCH_SIZE', 'DEFAULT_LAMBDA_PARAM',
           'DEFAULT_FORECAST_HORIZON', 'DEFAULT_MAX_P', 'DEFAULT_MAX_Q',
           'DEFAULT_GARCH_CRITERION', 'ANNUALIZATION_FACTOR', 'DEFAULT_ROLLING_WINDOW']
